parameters:
#    ens_login.example.class: Ens\LoginBundle\Example

services:
#    ens_login.example:
#        class: %ens_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
