parameters:
#    blog.example.class: Ens\BlogBundle\Example

services:
    blogger_blog.twig.extension:
        class: Ens\BlogBundle\Twig\Extensions\BlogExtension
        tags:
            - { name: twig.extension }
